# Single GitHub Action to run tests against the codebase
# This test includes integration tests and unit tests all in one.
name: CI - Tests

on:
  push:
    branches: [ "main" ]

env:
  # Setup some basic Environment Variables
  PORT: 8080
  DEBUGLOG: true
  CACHETIME: 600000
  PAGINATE: 30
  SERVERURL: "http://localhost:8080"
  NODE_ENV: "test"
  PULSAR_STATUS: "dev"  # This helps some modules know they are in a test environment

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Setup NodeJS - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Commit Coverage
        if: always() # Needed to ensure coverage is commit even on test failure.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GH Action Tests - Coverage Info

      - name: Coveralls Upload
        if: always() # Needed to ensure coverage is commited even on test failure
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
