# Single GitHub Action to run tests against the codebase
# This test includes integration tests and unit tests all in one.
name: CI - Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI - Standards" ]
    types:
      - completed
  # Using this to prevent simultaneous runs, outdating local git cache

env:
  # Setup some basic Environment Variables
  PORT: 8080
  DEBUGLOG: true
  CACHETIME: 600000
  PAGINATE: 30
  SERVERURL: "http://localhost:8080"
  NODE_ENV: "test"
  PULSAR_STATUS: "dev"  # This helps some modules know they are in a test environment
  # The following are useful to be able to test the git module
  # But ideally there could be found a better solution than this.
  # The same isn't done in the PR tests so that users don't have bad access to token during runs.
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_USERNAME: "confused-Techie"
  GH_USERAGENT: "Pulsar GHAction Tester Bot"

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Setup NodeJS - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Codecov Upload
        if: always() # Needed to ensure coverage is commited even on test failure
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml

      #- name: Coveralls Upload
        #if: always() # Needed to ensure coverage is commited even on test failure
        #uses: coverallsapp/github-action@master
        #with:
          #github-token: ${{ secrets.GITHUB_TOKEN }}
