# Single GitHub Action to run all types of tests. But only runs on a PR, and does
# not commit any changes, nor upload them to coveralls
name: CI - Tests PR

on:
  pull_request:
  workflow_dispatch:

env:
  # Setup some basic Environment Variables
  PORT: 8080
  DEBUGLOG: true
  CACHETIME: 600000
  PAGINATE: 30
  SERVERURL: "http://localhost:8080"
  NODE_ENV: "test"
  PULSAR_STATUS: "dev"  # This helps some modules know they are in a test environment
  GH_USERAGENT: "Pulsar-Edit Tester Bot"

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Setup NodeJS - ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test
