# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Specifically will run linting, docs, and complexity reports.

name: Node.js CI - Lint, Docs, Complexity Reports

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      # While originally this was --only=dev, seems by default install will install dev-dependencies
    - run: npm run lint
    - run: npm run api-docs
    - run: npm run js-docs
    - run: npm run complex
    - name: Commit Auto Lint, Complexity, Docs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply Linting, Complexity, Docs changes
